server {
    listen 80;
    server_name app.local.test;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name app.local.test;

    #ssl_certificate /etc/nginx/certs/app.local.test.crt;
    #ssl_certificate_key /etc/nginx/certs/app.local.test.key;
    ssl_certificate /etc/nginx/certs/app.local.wrong.crt;
    ssl_certificate_key /etc/nginx/certs/app.local.wrong.key;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}